### ISSUE TITLE
How to handle N/A?

### ISSUE THREAD

**Issue by jberkus** [cornelius/open-source-governance#1]
How should values which are "not applicable" or "does not exist" be handled?

For example, if an organzation specifically does not publish an annual report, what should we put for "annual report"?  Simply omitting the attribute implies that we don't know.

**Comment by ShaneCurcuru** [comment]
If we want to be detailed, it may vary depending on the field.  But for many fields, it might be values like:
- Not yet checked (i.e. someone submitted an entry, but without all details, and we don't know if someone's looked or not)
- Looked but no data found (a project maintainer has made a good faith effort to find the data in obvious public places, but failed to find it)
- Does not apply to this entry (i.e. non-profit status details for a for-profit company)

**Comment by cornelius** [comment]
I was implicitly using the convention of putting a value of "?" for "not yet checked" and an empty string for "not available". We could represent "does not apply" by using a nil value.

An alternative would be to use text keywords, "not-yet-checked", "no-data-found", "does-not-apply".

**Comment by jberkus** [comment]
Yeah, we can do a bunch of things, I'm asking for some standard values here.  Proposed:

* unknown or ? : has not been checked
* none : project specifically does not have
* not applicable : project does not have because it wouldn't make any sense (e.g. organization_maximum_corporate_membership_fee only makes sense for 501(c)6s, so is "not applicable" for everyone else)
